import { createOldTimeSpheres } from "./old-time-spheres.js?v=mega-2";
// Old Time landscape and cash trails. Normal world visibility is restored after every render.
export function createOldTime(THREE,api){
 const {scene,taxi,ground,coast,roads,terrainHeight,roadWidthForType,convertPosition,nearestDrivePoint}=api;
 let active=false,cooldown=0;const previous=taxi.position.clone();
 const world=new THREE.Group();world.name='Old Time landscape';world.visible=false;scene.add(world);
 const portalRoot=new THREE.Group();portalRoot.name='Old Time portals';scene.add(portalRoot);
 const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:1});
 const grass=mat(0x7c8c54),dirt=mat(0x9e9678),shingle=mat(0x9e967e);
 // World-space mottling keeps the prototype texture small and stable while driving.
 function mottled(m,tracks=false){m.onBeforeCompile=s=>{s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 oldWorld;').replace('#include <begin_vertex>','#include <begin_vertex>\noldWorld=(modelMatrix*vec4(position,1.)).xyz;');s.fragmentShader=s.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 oldWorld;').replace('#include <color_fragment>',`#include <color_fragment>
 float broad=sin(oldWorld.x*.043+sin(oldWorld.z*.06))*sin(oldWorld.z*.039);float fleck=fract(sin(dot(floor(oldWorld.xz*8.),vec2(12.9898,78.233)))*43758.5453);diffuseColor.rgb*=.90+.10*broad+.10*fleck;`);};m.customProgramCacheKey=()=>tracks?'old-tracks-v1':'old-grass-v1';}
 mottled(grass);mottled(dirt,true);mottled(shingle);
 const dirtCompile=dirt.onBeforeCompile;dirt.onBeforeCompile=s=>{dirtCompile(s);s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\nvarying vec2 oldTrack;').replace('#include <begin_vertex>','#include <begin_vertex>\noldTrack=uv;');s.fragmentShader=s.fragmentShader.replace('#include <common>','#include <common>\nvarying vec2 oldTrack;').replace('#include <color_fragment>',`#include <color_fragment>
 float uneven=.035*sin(oldTrack.y*1.7)+.025*sin(oldTrack.y*4.1);float centre=1.-smoothstep(.04,.17+uneven,abs(oldTrack.x));float verge=smoothstep(.58+uneven,.96,abs(oldTrack.x));diffuseColor.rgb=mix(diffuseColor.rgb,vec3(.202,.262,.089),max(centre*.78,verge));`);};
 const values=new Float32Array(coast.rows.length*4);coast.rows.forEach((r,i)=>values.set([r.edge,0,0,0],i*4));const lookup=new THREE.DataTexture(values,coast.rows.length,1,THREE.RGBAFormat,THREE.FloatType);lookup.needsUpdate=true;lookup.minFilter=lookup.magFilter=THREE.NearestFilter;
 const landMaterial=grass.clone();mottled(landMaterial);const noiseCompile=landMaterial.onBeforeCompile;
 landMaterial.onBeforeCompile=s=>{noiseCompile(s);s.uniforms.oldCoast={value:lookup};s.fragmentShader=s.fragmentShader.replace('#include <common>','#include <common>\nuniform sampler2D oldCoast;').replace('#include <clipping_planes_fragment>',`#include <clipping_planes_fragment>
 if(oldWorld.x>=${coast.minX.toFixed(4)}&&oldWorld.x<=${coast.maxX.toFixed(4)}){float f=(oldWorld.x-(${coast.minX.toFixed(4)}))/${(coast.maxX-coast.minX).toFixed(4)}*${coast.rows.length-1}.;float i=floor(f);float edge=mix(texture2D(oldCoast,vec2((i+.5)/${coast.rows.length}.,.5)).r,texture2D(oldCoast,vec2((min(i+1.,${coast.rows.length-1}.)+.5)/${coast.rows.length}.,.5)).r,fract(f));if(oldWorld.z>edge)discard;}`);};landMaterial.customProgramCacheKey=()=> 'old-land-clipped-v1';
 const land=new THREE.Mesh(ground.geometry.clone(),landMaterial);land.position.copy(ground.position);land.receiveShadow=true;world.add(land);
 function surface(x,z){const r=coast.promenadeAt(x);if(!r||z<r.edge)return terrainHeight(x,z);const shore=r.prom+10;if(z<shore)return THREE.MathUtils.lerp(terrainHeight(x,r.edge),.3,(z-r.edge)/(shore-r.edge));return THREE.MathUtils.lerp(.3,-.15,THREE.MathUtils.clamp((z-shore)/(r.sea-shore),0,1));}
 function strip(material,left,right){const v=[];for(let i=1;i<coast.rows.length;i++){const a=coast.rows[i-1],b=coast.rows[i];for(const p of [left(a),right(b),left(b),left(a),right(a),right(b)])v.push(...p);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.computeVertexNormals();const mesh=new THREE.Mesh(g,material);mesh.receiveShadow=true;world.add(mesh);}
 strip(grass,r=>[r.x,terrainHeight(r.x,r.edge)-.18,r.edge],r=>[r.x,.3,r.prom+10]);
 strip(shingle,r=>[r.x,.3,r.prom+10],r=>[r.x,-.15,r.sea]);
 const water=api.waterMaterial.clone();water.depthTest=true;water.depthWrite=true;
 strip(water,r=>[r.x,-.15,r.sea],r=>[r.x,-.15,8000]);
 // The saved road centre lines remain the driving network beneath these dirt tracks.
 const track=[],trackUV=[];for(const s of roads){const dx=s.b.x-s.a.x,dz=s.b.z-s.a.z,len=Math.hypot(dx,dz);if(len<.2)continue;const nx=-dz/len,nz=dx/len,w=roadWidthForType(s.type)*.5,n=Math.ceil(len/6);const p=(t,side)=>{const x=s.a.x+dx*t+nx*w*side,z=s.a.z+dz*t+nz*w*side;return [x,terrainHeight(x,z)+.045,z,side,len*t]};for(let i=0;i<n;i++)for(const q of [p(i/n,-1),p((i+1)/n,1),p((i+1)/n,-1),p(i/n,-1),p(i/n,1),p((i+1)/n,1)]){track.push(...q.slice(0,3));trackUV.push(q[3],q[4]);}}
 const trackGeo=new THREE.BufferGeometry();trackGeo.setAttribute('position',new THREE.Float32BufferAttribute(track,3));trackGeo.setAttribute('uv',new THREE.Float32BufferAttribute(trackUV,2));trackGeo.computeVertexNormals();const tracks=new THREE.Mesh(trackGeo,dirt);tracks.receiveShadow=true;world.add(tracks);
 const entry=api.portalEntry||nearestDrivePoint(convertPosition(50.85255,.5664)),leave=nearestDrivePoint(convertPosition(50.85215,.5643));
 let yaw=Math.atan2(-(entry.segment.b.x-entry.segment.a.x),-(entry.segment.b.z-entry.segment.a.z));if(-Math.sin(yaw)>0)yaw+=Math.PI;
 function gate(road,label,colour){const g=new THREE.Group(),ring=new THREE.Mesh(new THREE.TorusGeometry(3.3,.15,6,40),new THREE.MeshBasicMaterial({color:colour}));g.add(ring);g.position.set(road.point.x,terrainHeight(road.point.x,road.point.z)+3.4,road.point.z);g.rotation.y=yaw;
 if(label){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#192820';ctx.fillRect(0,0,512,128);ctx.fillStyle='#f7edc9';ctx.textAlign='center';ctx.font='bold 48px sans-serif';ctx.fillText(label,256,57);ctx.font='24px sans-serif';ctx.fillText('DRIVE THROUGH',256,99);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const sign=new THREE.Sprite(new THREE.SpriteMaterial({map:tex}));sign.position.y=4.25;sign.scale.set(6,1.5,1);g.add(sign);}portalRoot.add(g);return g;}
 const entrance=gate(entry,null,0xd8cb79),exit=gate(leave,'RETURN TO HASTINGS',0x9ccfa9);exit.visible=false;
 const spheres=createOldTimeSpheres(THREE,{world,roads,entry:entry.point,exit:leave.point,surface,award:api.awardCash});
 // Modest instanced vegetation around the first playable coastal area.
 let seed=908;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};
 const shrubGeo=new THREE.IcosahedronGeometry(1,1),trunkGeo=new THREE.CylinderGeometry(.16,.24,1,6),greens=[0x596b3c,0x718049,0x465f3e,0x8d9153].map(mat),bark=mat(0x69573f),batches=new Map(),dummy=new THREE.Object3D();
 function plant(geo,m,x,y,z,sx,sy,sz){let list=batches.get(m);if(!list)batches.set(m,list={geo,matrices:[]});dummy.position.set(x,y,z);dummy.scale.set(sx,sy,sz);dummy.rotation.set(0,rand()*6.28,0);dummy.updateMatrix();list.matrices.push(dummy.matrix.clone());}
 let plants=0;for(let i=0;i<1900;i++){const close=i>=1600,x=entry.point.x+(rand()-.5)*(close?550:1800),z=entry.point.z-(close?100:90)+(rand()-.5)*(close?200:1400),r=coast.promenadeAt(x);if(r&&z>r.edge-8)continue;const near=nearestDrivePoint({x,z});if(!near||near.distance<roadWidthForType(near.segment.type)/2+5)continue;const y=terrainHeight(x,z),tree=rand()>.75,size=tree?2+rand()*2.6:.6+rand()*1.2;if(tree){plant(trunkGeo,bark,x,y+size*.65,z,1,size*1.3,1);for(let j=0;j<3;j++)plant(shrubGeo,greens[j%3],x+(j-1)*size*.45,y+size*(1.2+(j===1?.3:0)),z+(rand()-.5)*size*.4,size*.8,size*.65,size*.75);}else plant(shrubGeo,greens[i%4],x,y+size*.45,z,size,size*.6,size*.8);plants++;}
 for(const [m,b]of batches){const mesh=new THREE.InstancedMesh(b.geo,m,b.matrices.length);b.matrices.forEach((v,i)=>mesh.setMatrixAt(i,v));mesh.castShadow=true;mesh.receiveShadow=true;mesh.computeBoundingSphere();world.add(mesh);}
 const style=document.createElement('style');style.textContent='body.old-time #job,body.old-time #guidance,body.old-time #pickupHUD,body.old-time #hyperHUD,body.old-time #dialogue{display:none!important}#oldTimeBadge{position:fixed;top:14px;left:50%;transform:translateX(-50%);padding:9px 16px;background:#26352be8;color:#efe6bc;border:1px solid #ada779;border-radius:7px;font:13px system-ui;z-index:1110;pointer-events:none}body.hud-clean #oldTimeBadge{display:none}';document.head.append(style);
 const badge=document.createElement('div');badge.id='oldTimeBadge';badge.hidden=true;document.body.append(badge);
 function crossing(g){const a=previous,b=taxi.position,dx=b.x-a.x,dz=b.z-a.z;if(dx*dx+dz*dz>900)return false;const t=THREE.MathUtils.clamp(((g.position.x-a.x)*dx+(g.position.z-a.z)*dz)/(dx*dx+dz*dz||1),0,1);return Math.hypot(a.x+t*dx-g.position.x,a.z+t*dz-g.position.z)<2.7;}
 function update(dt){cooldown=Math.max(0,cooldown-dt);portalRoot.visible=!api.blocked();if(!api.blocked()&&cooldown===0&&crossing(active?exit:entrance)){active=!active;if(!active){taxi.position.set(leave.point.x,terrainHeight(leave.point.x,leave.point.z)+.15,leave.point.z);taxi.rotation.y=Math.atan2(-(leave.segment.b.x-leave.segment.a.x),-(leave.segment.b.z-leave.segment.a.z));}spheres.reset();cooldown=3;world.visible=active;entrance.visible=!active;exit.visible=active;badge.hidden=!active;document.body.classList.toggle('old-time',active);api.onSwitch(active);}
 if(active){spheres.update(previous,taxi.position);badge.textContent='OLD TIME · Red spheres '+spheres.count+'/'+spheres.total+' · +£'+(spheres.earned/100).toFixed(2)+' · Cash £'+(api.getCash()/100).toFixed(2)+' · Return '+Math.round(taxi.position.distanceTo(exit.position))+' m';}previous.copy(taxi.position);}
 function render(renderer,camera,after){if(!active)return false;const visibility=[],gullPositions=[];const keep=new Set([taxi,world,portalRoot,...api.getGullGroups()]);for(const o of scene.children){visibility.push([o,o.visible]);const weather=o.material?.uniforms?.skyTint===undefined&&o.renderOrder===-40;const light=o.isLight&&!o.isPointLight;const allowed=keep.has(o)||weather||light||o===api.rain; o.visible=allowed&&o.visible;}
 for(const b of api.getBirds()){if(['walk','perch'].includes(b.state)){gullPositions.push([b.g,b.g.position.y]);b.g.position.y=surface(b.g.position.x,b.g.position.z)+.38;}}
 water.color.copy(api.waterMaterial.color);try{renderer.render(scene,camera);after?.();}finally{for(const [o,v]of visibility)o.visible=v;for(const [g,y]of gullPositions)g.position.y=y;}return true;}
 return {spheres,update,render,surface,isSea:(x,z)=>{const r=coast.promenadeAt(x);return r?z>=r.sea:false},entry:entry.point,yaw,exit:leave.point,plants,get active(){return active}};
}
